/* Original instrumental arrangements. No commercial recordings or external media streams. */
(() => {
  'use strict';
  class HarbourAudio{
    constructor(){this.ctx=null;this.musicOn=true;this.sfxOn=true;this.playing=false;this.timer=null;this.step=0;this.track=0;this.next=0;this.nodes=new Set();try{this.musicOn=localStorage.getItem('harbour.music')!=='off';this.sfxOn=localStorage.getItem('harbour.sound')!=='off';this.track=Number(localStorage.getItem('harbour.track')||0)%2;}catch(_){} }
    ensure(){try{if(!this.ctx){const A=window.AudioContext||window.webkitAudioContext;if(!A)return false;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.5;const comp=this.ctx.createDynamicsCompressor();comp.threshold.value=-18;comp.knee.value=14;comp.ratio.value=3;this.master.connect(comp);comp.connect(this.ctx.destination);this.music=this.ctx.createGain();this.music.gain.value=.5;this.music.connect(this.master);this.fx=this.ctx.createGain();this.fx.gain.value=.75;this.fx.connect(this.master);const b=this.ctx.createBuffer(1,this.ctx.sampleRate,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=(last+.025*(Math.random()*2-1))/1.025;d[i]=last*8;}this.noise=b;}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});return true;}catch(_){return false;}}
    freq(n){return 440*Math.pow(2,(n-69)/12);}
    note(n,t,d=.2,v=.09,type='keys',bus=this.music){if(!this.ctx||!bus)return;const c=this.ctx,g=c.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);g.connect(bus);const harmonics=type==='bass'?[[1,1],[2,.14]]:type==='bell'?[[1,1],[2.76,.15],[4.01,.06]]:[[1,1],[2,.22],[3,.075]];for(const [ratio,amp]of harmonics){const o=c.createOscillator(),a=c.createGain();o.type='sine';o.frequency.value=this.freq(n)*ratio;a.gain.value=amp;o.connect(a);a.connect(g);o.start(t);o.stop(t+d+.03);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);o.disconnect();a.disconnect();};}setTimeout(()=>g.disconnect(),Math.max(0,(t-c.currentTime+d+.15)*1000));}
    drum(type,t){const c=this.ctx,g=c.createGain();g.connect(this.music);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(type==='kick'?.14:.05,t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+(type==='kick'?.19:.08));if(type==='kick'){const o=c.createOscillator();o.frequency.setValueAtTime(118,t);o.frequency.exponentialRampToValueAtTime(45,t+.15);o.connect(g);o.start(t);o.stop(t+.21);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);o.disconnect();g.disconnect();};}else{const s=c.createBufferSource(),f=c.createBiquadFilter();s.buffer=this.noise;f.type='highpass';f.frequency.value=type==='hat'?6500:1800;s.connect(f);f.connect(g);s.start(t,Math.random()*.5);s.stop(t+.09);this.nodes.add(s);s.onended=()=>{this.nodes.delete(s);s.disconnect();f.disconnect();g.disconnect();};}}
    sequence(){if(!this.playing||!this.musicOn||!this.ctx)return;const c=this.ctx,bpm=this.track===0?112:118,eighth=60/bpm/2;if(this.next<c.currentTime-.15)this.next=c.currentTime+.04;while(this.next<c.currentTime+.2){const s=this.step%128,bar=Math.floor(s/8),beat=s%8,progressions=[[60,64,67,71],[57,60,64,67],[53,57,60,64],[55,59,62,65]],chord=progressions[bar%4];if(beat===0||beat===3||beat===6){for(const n of chord)this.note(n,this.next,.65,.026,'keys');}if(beat===0||beat===4||((this.track===1)&&beat===7))this.note(chord[0]-24+(beat===4?7:0),this.next,.27,.12,'bass');if(beat===0||beat===4)this.drum('kick',this.next);if(beat===2||beat===6)this.drum('snare',this.next);if(beat%2===1)this.drum('hat',this.next);
      const melodies=[[76,79,83,81,79,76,74,71],[72,-1,76,79,81,79,76,-1],[69,72,76,79,76,-1,74,72],[71,74,77,79,77,74,71,-1],[79,83,86,-1,83,81,79,76],[76,79,81,84,83,79,-1,76],[72,76,79,-1,76,74,72,69],[74,-1,77,81,79,77,74,-1]];const n=melodies[bar%8][beat];if(n>0){const octave=this.track===1&&bar%4===2?-12:0;this.note(n+octave,this.next,.23,.061,this.track===0?'bell':'keys');}this.step++;this.next+=eighth;} }
    start(){this.playing=true;if(!this.ensure())return;this.stopTimer();if(this.musicOn){this.music.gain.setTargetAtTime(.45,this.ctx.currentTime,.12);this.next=this.ctx.currentTime+.04;this.sequence();this.timer=setInterval(()=>this.sequence(),60);}}
    stopTimer(){if(this.timer){clearInterval(this.timer);this.timer=null;}}
    pause(){this.playing=false;this.stopTimer();if(this.ctx)this.music.gain.setTargetAtTime(.0001,this.ctx.currentTime,.05);}
    toggleMusic(){this.musicOn=!this.musicOn;try{localStorage.setItem('harbour.music',this.musicOn?'on':'off');}catch(_){}if(this.playing){if(this.musicOn)this.start();else{this.stopTimer();if(this.ctx)this.music.gain.setTargetAtTime(.0001,this.ctx.currentTime,.03);}}return this.musicOn;}
    toggleEffects(){this.sfxOn=!this.sfxOn;try{localStorage.setItem('harbour.sound',this.sfxOn?'on':'off');}catch(_){}if(this.ctx)this.fx.gain.setTargetAtTime(this.sfxOn?.75:.0001,this.ctx.currentTime,.015);return this.sfxOn;}
    switchTrack(){this.track=1-this.track;this.step=0;try{localStorage.setItem('harbour.track',String(this.track));}catch(_){}if(this.playing)this.start();return this.track;}
    effect(kind,tier=0){if(!this.sfxOn||!this.ensure())return;this.fx.gain.setTargetAtTime(.75,this.ctx.currentTime,.01);const at=this.ctx.currentTime,parts={hop:[[69,0,.07]],duck:[[52,0,.06]],flower:[[83,0,.08],[88,.05,.1]],gold:[[79,0,.11],[83,.06,.12],[88,.13,.19]],milestone:[[72,0,.1],[76,.08,.12],[79,.16,.24]],start:[[67,0,.09],[72,.08,.12]],splash:[[46,0,.12],[41,.08,.17]],result:tier<2?[[67,0,.12],[72,.13,.24]]:[[72,0,.12],[76,.11,.13],[79,.22,.14],[84,.34,.32]]};for(const [n,delay,d]of (parts[kind]||parts.flower))this.note(n,at+delay,d,.12,'bell',this.fx);}
    diagnostic(){return{music:this.musicOn,effects:this.sfxOn,playing:this.playing,track:this.track,context:this.ctx?.state||'not-started',scheduledNodes:this.nodes.size};}
  }
  window.HarbourAudio=HarbourAudio;
})();
